services:
  rahoot:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./config:/app/config
    environment:
      - WEB_ORIGIN=http://37.97.134.41:3000
      - SOCKET_URL=http://37.97.134.41:3001

