FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages/web/package.json ./packages/web/
COPY packages/socket/package.json ./packages/socket/
COPY packages/common/package.json ./packages/common/

RUN pnpm install --frozen-lockfile

CMD ["pnpm", "-r", "--parallel", "dev"]
